name: Deploy Dist
on: [push,workflow_dispatch]
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Get code
              run: |
                echo "cloning repo to the ubuntu server"
                echo "${{toJson(github)}}"
                git clone https://github.com/${{github.repository}}/githubActions-cicd-project.git